### ISSUE TITLE
SSL certificate expired on official RYO pool

### ISSUE THREAD

**Issue by LeadManPL** [ryo-currency/ryo-pools-json#6]
As in subject, SSL cert for pool.ryo-currency.com expired on 2018-12-28
Please generate new cert as it is impossible to mine via SSL

**Comment by mosu-forge** [comment]
Are you mining to one of the ssl ports or are you having problems accessing the frontend? Regular ports are working and we have many miners connected, but I will check the ssl ports if that is what you are having problems with.

**Comment by LeadManPL** [comment]
Closing, as apparently I am able to connect to pool.ryo-currency.com:4445 with  xmrig-amd miner
