### ISSUE TITLE
Login error: your IP is banned

### ISSUE THREAD

**Issue by LeadManPL** [ryo-currency/ryo-pools-json#9]
After 2019-02-14 in new RYO blockchain version, on official pool  https://pool.ryo-currency.com:4445 , i started to get information:
"Login error: your IP is banned"
Last accepted share i see in log file is 2019-02-15 12:41:07
I was informed by @psychocrypt  in https://github.com/fireice-uk/xmr-stak/pull/2192  that xmr-stak 2.8.0 will auto-switch to new algo.
What might be the reason for this ban of my IP ?

**Comment by mosu-forge** [comment]
@LeadManPL xmr stak should have switched, but use cryptonight_gpu to be sure. Bans only last for 10 minutes, but if you ever do get banned again you can try another pool from: pools.ryoblocks.com

**Comment by LeadManPL** [comment]
ok, thx for the info. Closing.
